pipeline {
    agent none
    stages {
        stage ('Back-end') {
            agent {
                docker {
                    image 'maven:3.3.3'
                }
            }
            steps {
                sh 'mvn --version'
            }
        }
        stage ('Front-end') {
            agent {
                docker {
                    image 'node:7-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }
        stage ('DB'){
            agent {
                docker {
                    image 'mysql:5.7'
                }
            }
            steps {
                sh 'mysql --version'
            }
        }
    }
}
