pipeline {
    agent {
        docker {
            image 'node:16-alpine' // Corrected image name
        }
    }
    stages {
        stage ('Test') {
            steps {
                sh 'node --version'
            }
        }
    }
}
